app:
  version: 1.0
  env: ${APP_ENV:dev}
  logoutUrl: ${LOGOUT_URL:https://casuat.chowsangsang.com/cas/logout}

spring:
  application:
    name: personalization-admin
  jackson:
    default-property-inclusion: non_null
  datasource:
    initialize: false
    pers:
      driver: oracle.jdbc.OracleDriver
      url: ${DB_URL_PERS:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hkracdev01.chowsangsang.com)(PORT=1521))(LOAD_BALANCE=yes)(FAILOVER=on)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=persdev)))}
      username: diy_app
      password: ${DB_PW_PERS_DIY_APP:diy_app}
      poolMaximumActiveConnections: ${DB_MAX_ACTIVE_CONN:8}
      poolMaximumIdleConnections: ${DB_MAX_IDLE_CONN:2}
      poolMaximumCheckoutTime: ${DB_MAX_CHECKOUT_TIME:60000}
      poolTimeToWait: ${DB_TIME_TO_WAIT:15000}
      poolMaximumLocalBadConnectionTolerance: ${DB_MAX_BAD_CONN:3}
      poolPingQuery: ${DB_PING_QUERY:NO PING QUERY SET}
      poolPingEnabled: ${DB_PING_ENABLED:false}
      poolPingConnectionsNotUsedFor: ${DB_PING_NOT_USED_FOR:300000}
      
    alpha:
      driver: oracle.jdbc.OracleDriver
      url: ${DB_URL_ALPHA:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hkdevdb3.chowsangsang.com)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=alphadv4)(SERVER=DEDICATED))(LOAD_BALANCE=yes)(FAILOVER=on))}
      username: diy_app
      password: ${DB_PW_ALPHA_DIY_APP:diy_app}
      poolMaximumActiveConnections: ${DB_MAX_ACTIVE_CONN:8}
      poolMaximumIdleConnections: ${DB_MAX_IDLE_CONN:2}
      poolMaximumCheckoutTime: ${DB_MAX_CHECKOUT_TIME:60000}
      poolTimeToWait: ${DB_TIME_TO_WAIT:15000}
      poolMaximumLocalBadConnectionTolerance: ${DB_MAX_BAD_CONN:3}
      poolPingQuery: ${DB_PING_QUERY:NO PING QUERY SET}
      poolPingEnabled: ${DB_PING_ENABLED:false}
      poolPingConnectionsNotUsedFor: ${DB_PING_NOT_USED_FOR:300000}
      
    shpd:
      driver: oracle.jdbc.OracleDriver
      url: ${DB_URL_SHPD:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hkdevdb3.chowsangsang.com)(PORT=1523))(CONNECT_DATA=(SERVICE_NAME=shdev4)(SERVER=DEDICATED))(LOAD_BALANCE=yes)(FAILOVER=on))}
      username: diy_app
      password: ${DB_PW_SHPD_DIY_APP:diy_app}
      poolMaximumActiveConnections: ${DB_MAX_ACTIVE_CONN:8}
      poolMaximumIdleConnections: ${DB_MAX_IDLE_CONN:2}
      poolMaximumCheckoutTime: ${DB_MAX_CHECKOUT_TIME:60000}
      poolTimeToWait: ${DB_TIME_TO_WAIT:15000}
      poolMaximumLocalBadConnectionTolerance: ${DB_MAX_BAD_CONN:3}
      poolPingQuery: ${DB_PING_QUERY:NO PING QUERY SET}
      poolPingEnabled: ${DB_PING_ENABLED:false}
      poolPingConnectionsNotUsedFor: ${DB_PING_NOT_USED_FOR:300000}
    
    twprod:
      driver: oracle.jdbc.OracleDriver
      url: ${DB_URL_TWPROD:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hkracdev01.chowsangsang.com)(PORT=1521))(LOAD_BALANCE=yes)(FAILOVER=on)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=twprodv5)))}
      username: diy_app
      password: ${DB_PW_TWPROD_DIY_APP:diy_app}
      poolMaximumActiveConnections: ${DB_MAX_ACTIVE_CONN:8}
      poolMaximumIdleConnections: ${DB_MAX_IDLE_CONN:2}
      poolMaximumCheckoutTime: ${DB_MAX_CHECKOUT_TIME:60000}
      poolTimeToWait: ${DB_TIME_TO_WAIT:15000}
      poolMaximumLocalBadConnectionTolerance: ${DB_MAX_BAD_CONN:3}
      poolPingQuery: ${DB_PING_QUERY:NO PING QUERY SET}
      poolPingEnabled: ${DB_PING_ENABLED:false}
      poolPingConnectionsNotUsedFor: ${DB_PING_NOT_USED_FOR:300000}
  messages:
    use-code-as-default-message: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: true
    show-sql: false
    hibernate:
      hbm2ddl.auto: none
      ddl-auto: none
    properties:
      hibermate:
        show_sql: false


server:
  port: ${SPRING_SERVER_PORT:10005}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 2048

project:
  package: com.css.misc.personalization.admin

#############################################
# EUREKA CLIENT CONFIGURATION#
#############################################
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://hkapiproxysit01.chowsangsang.com:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

# logging
logging:
  level:
    root: INFO
    org:
      hibernate.SQL: DEBUG
    com:
      css:
        misc:
          personalization:
            admin:
              dao: DEBUG
              controller: DEBUG

debug: false

# feign
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 20000
        loggerLevel: FULL
        errorDecoder: com.css.cloud.config.feign.ErrorDecoder
        encoder: com.css.cloud.config.feign.GsonEncoder
        decoder: com.css.cloud.config.feign.GsonDecoder
  compression:
    request:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,application/xml,text/javascript,application/javascript,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: true
    disableSslValidation: true







management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled:
          true
          

idempotent:
  datasource:
    driver: oracle.jdbc.OracleDriver
    url: ${DB_URL_PERS:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hkracdev01.chowsangsang.com)(PORT=1521))(LOAD_BALANCE=yes)(FAILOVER=on)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=persdev)))}
    username: diy_app
    password: ${DB_PW_PERS_DIY_APP:diy_app}